### ISSUE TITLE
Create Order Panic Error

### ISSUE THREAD

**Issue by khanakia** [razorpay/razorpay-go#22] opened 2020-11-26 12:52 UTC
I am using the correct test key and secret and getting error

```
map[]
%!v(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
```

```
package main

import (
	"fmt"

	"github.com/razorpay/razorpay-go"
)

func main() {
	client := razorpay.NewClient("rzp_test_9lsYF6ARKRbVbs", "l4KsqSMSB02smJBnVJgZPRmE")
	data := map[string]interface{}{
		"amount":          1234,
		"currency":        "INR",
		"receipt_id":      "some_receipt_id",
		"payment_capture": 1,
	}

	extraHeaders := map[string]string{}

	body, err := client.Order.Create(data, extraHeaders)
	fmt.Println(body)
	fmt.Println(err)

}
```

**Comment by salsanej** [comment] 2020-12-02 11:37
Getting the same error:
```
map[]
%!v(PANIC=runtime error: invalid memory address or nil pointer dereference)
```

Is it a working repository or just wasting our time?

**Comment by khanakia** [comment] 2020-12-02 12:05
@salsanej Repo is working but they have bug in error reporting so it will not reveal you actual error from the api. So you just have to make sure are you posting the right data to the api. 

If you really want to see the error then you have to make edit to this file for now `vendor/github.com/razorpay/razorpay-go/requests/request.go` in `doRequestResponse` func

**Comment by HarishJagtap** [comment] 2021-08-08 07:50
@venkatvghub
I have added a fix for this and created pull request.

**Comment by dsouzadyn** [comment] 2022-04-21 10:50
hi can we get this issue fixed on priority

**Comment by ashwinimanoj** [comment] 2022-06-21 11:25
Seems to be fixed in #58

**Comment by ankitdas13** [comment] 2022-10-26 08:33
@khanakia Thanks for reporting this issue . It has already been fixed in one of recent releases. Please update to the most recent version to resolve this issue.

Closing this issue for now, Please don't let that stop you from re-opening if the issue is persisting for you.

**Closed by ankitdas13** 2022-10-26 08:33 UTC
